### ISSUE TITLE
MERCURE_PUBLISH_URL ignored ?

### ISSUE THREAD

**Issue by Soonz** [symfony/mercure-bundle#41]
Hello,

I'm having a weird issue with Mercure, here's my .env file :

MERCURE_PUBLISH_URL=http://whateverurl/.well-known/mercure

When I output it like so : 
```
parameters:
    test: '%env(MERCURE_PUBLISH_URL)%'
```

In a controller : `dd( $this->getParameter( 'test' ) );`

I get : `http://127.0.0.1:8000/.well-known/mercure`

I'm trying on a Windows machine, I use Symfony 5.2.4, fresh install with Mercure Bundle 0.2.6

**Comment by ziat1988** [comment]
I have same problem. Why in .env I set MERCURE_PUBLISH_URL=http://mercure/.well-known/mercure or whatever url
Then if I do   $this->getParameter('mercure.default_hub') I always have http://127.0.0.1:8000/.well-known/mercure
And It is not the port 3000 like the doc said

**Comment by raf59** [comment]
Hi !
I'm also getting the same issue. 
I have not found any way to override the mercure publish url nor the mercure jwt token. 
The changes in .env file have no effect.

**Comment by ochov1** [comment]
I have the same issue,

**Comment by azjezz** [comment]
this is a bug in symfony cli ( see https://github.com/symfony/cli/issues/427 )

I think this issue can be closed. 🙂

**Comment by chalasr** [comment]
Thank you.

**Comment by Soonz** [comment]
> there is some workaround for this or we must wait for some symfony updates?
> thank you.

In your config/packages/mercure.yaml you can temporarily do that until the CLI gets updated :

```
mercure:
    enable_profiler: '%kernel.debug%'
    hubs:
        default:
            url: '%env(MERCURE_PUBLISH_URL)%' // hardcode your desired URL
            jwt: '%env(MERCURE_JWT_TOKEN)%'
```
