### ISSUE TITLE
DI container cannot be built without valid JWT key

### ISSUE THREAD

**Issue by alex-dev** [symfony/mercure-bundle#95]
`lcobucci/jwt@^4|^5` validate keys. Building DI container should be doable without any env var setup.

```yaml
mercure:
  hubs:
    default:
      url: '%env(MERCURE_URL)%'
      public_url: '%env(MERCURE_PUBLIC_URL)%'
      jwt:
        secret: '%env(MERCURE_JWT_KEY)%'
        publish: ["*"]
        subscribe: ["*"]
```

Run `php bin/console cache:warmup` without providing  `MERCURE_JWT_KEY`
